/**
 * Social & Communication Types
 *
 * Types for group chat, trash talk, photo gallery, polls,
 * and social features.
 */

import type { UUID, ISODateString } from './models';

// ============================================
// GROUP CHAT
// ============================================

export type MessageType = 'text' | 'image' | 'gif' | 'poll' | 'system' | 'score_update';

export interface ChatMessage {
    id: UUID;
    tripId: UUID;
    threadId?: UUID; // For thread organization
    authorId: UUID;
    senderId: UUID;
    senderName: string;
    type: MessageType;
    content: string;
    imageUrl?: string;
    gifUrl?: string;
    pollId?: UUID;
    mentions?: UUID[]; // Player IDs mentioned with @
    replyToId?: UUID; // ID of message being replied to
    reactions: MessageReaction[];
    isEdited: boolean;
    isDeleted: boolean;
    timestamp: ISODateString;
    createdAt: ISODateString;
    updatedAt?: ISODateString;
}

export interface MessageReaction {
    emoji: string;
    playerIds: UUID[];
}

export interface ChatThread {
    id: UUID;
    tripId: UUID;
    name: string;
    type: 'main' | 'team_a' | 'team_b' | 'captains' | 'custom';
    participantIds: UUID[];
    lastMessageAt?: ISODateString;
    unreadCount: number;
    createdAt: ISODateString;
}

// ============================================
// TRASH TALK BOARD
// ============================================

export type TrashTalkType = 'text' | 'meme' | 'gif' | 'image' | 'prediction' | 'taunt';

export interface TrashTalk {
    id: UUID;
    tripId: UUID;
    authorId: UUID;
    authorName: string;
    targetId?: UUID; // Alias for targetPlayerId
    type: TrashTalkType;
    content: string;
    imageUrl?: string;
    gifUrl?: string;
    targetPlayerId?: UUID; // Who's being called out
    targetTeam?: 'usa' | 'europe';
    memeTemplateId?: string;
    likes: UUID[]; // Player IDs who liked
    comments: TrashTalkComment[];
    isPinned: boolean;
    timestamp: ISODateString;
    createdAt: ISODateString;
}

export interface TrashTalkComment {
    id: UUID;
    authorId: UUID;
    authorName: string;
    content: string;
    createdAt: ISODateString;
}

export interface MemeTemplate {
    id: string;
    name: string;
    imageUrl: string;
    topTextPlaceholder: string;
    bottomTextPlaceholder: string;
    category: 'golf' | 'sports' | 'general' | 'custom';
}

// ============================================
// PHOTO GALLERY
// ============================================

export type PhotoCategory = 'action' | 'group' | 'scenic' | 'celebration' | 'funny' | 'other';

export interface Photo {
    id: UUID;
    tripId: UUID;
    albumId?: UUID;
    uploaderId: UUID;
    uploaderName: string;
    url: string;
    thumbnailUrl?: string;
    caption?: string;
    category: PhotoCategory;
    taggedPlayerIds: UUID[];
    matchId?: UUID;
    sessionId?: UUID;
    holeNumber?: number;
    location?: string;
    takenAt?: ISODateString;
    likes: UUID[];
    comments: PhotoComment[];
    isMomentOfTrip: boolean; // Nominated for "moment of the trip"
    momentVotes: UUID[];
    uploadedAt: ISODateString;
    createdAt: ISODateString;
}

export interface PhotoComment {
    id: UUID;
    authorId: UUID;
    authorName: string;
    content: string;
    createdAt: ISODateString;
}

export interface PhotoAlbum {
    id: UUID;
    tripId: UUID;
    name: string;
    description?: string;
    coverPhotoId?: UUID;
    photoIds: UUID[];
    isAutoGenerated: boolean;
    createdAt: ISODateString;
}

// ============================================
// POLLS
// ============================================

export type PollType = 'single' | 'multiple' | 'ranked';
export type PollStatus = 'active' | 'closed' | 'cancelled';
export type PollCategory = 'dinner' | 'activity' | 'schedule' | 'rules' | 'fun' | 'other';

export interface Poll {
    id: UUID;
    tripId: UUID;
    createdById: UUID;
    creatorId: UUID;
    creatorName: string;
    question: string;
    description?: string;
    type: PollType;
    category: PollCategory;
    options: PollOption[];
    status: PollStatus;
    allowAddOptions: boolean; // Can participants add options?
    isAnonymous: boolean;
    expiresAt?: ISODateString;
    closesAt?: ISODateString;
    createdAt: ISODateString;
    closedAt?: ISODateString;
}

export interface PollOption {
    id: UUID;
    text: string;
    emoji?: string;
    addedBy?: UUID;
    votes: UUID[]; // Player IDs who voted for this
    rank?: number; // For ranked choice
}

export interface PollVote {
    pollId: UUID;
    playerId: UUID;
    optionIds: UUID[];
    rankings?: { optionId: UUID; rank: number }[];
    votedAt: ISODateString;
}

// ============================================
// NEMESIS TRACKING
// ============================================

export interface HeadToHeadRecord {
    id: UUID;
    tripId?: UUID;
    player1Id: UUID;
    player2Id: UUID;
    // Lifetime stats
    player1Wins: number;
    player2Wins: number;
    halves: number;
    totalMatches: number;
    // Detailed breakdown by format
    singlesRecord: { p1: number; p2: number; halves: number };
    foursomesRecord: { p1: number; p2: number; halves: number };
    fourballRecord: { p1: number; p2: number; halves: number };
    // Recent form (last 5 matches)
    recentResults: ('p1' | 'p2' | 'halve')[];
    // Streaks
    currentStreak: { player: 'p1' | 'p2' | null; count: number };
    longestStreak: { player: 'p1' | 'p2'; count: number };
    // Last match info
    lastMatchDate?: ISODateString;
    lastMatchTripId?: UUID;
    lastMatchResult?: 'p1' | 'p2' | 'halve';
    // Fun facts
    biggestWinMargin: { player: 'p1' | 'p2'; margin: string };
    mostDramaticMatch?: string;
    updatedAt: ISODateString;
}

export interface NemesisStats {
    playerId: UUID;
    nemesisId?: UUID; // Worst record against
    nemesisRecord?: string; // e.g., "1-5-0"
    bestMatchupId?: UUID; // Best record against
    bestMatchupRecord?: string;
    totalOpponents: number;
    overallRecord: { wins: number; losses: number; halves: number };
}

// ============================================
// TRIP ARCHIVE
// ============================================

export interface TripArchive {
    id: UUID;
    tripId: UUID;
    tripName: string;
    location: string;
    startDate: ISODateString;
    endDate: ISODateString;
    // Results
    winner: 'usa' | 'europe' | 'tie';
    finalScore: { teamA: number; teamB: number };
    teamAName: string;
    teamBName: string;
    // Participants
    playerCount: number;
    players: ArchivedPlayer[];
    // Statistics
    totalMatches: number;
    totalHolesPlayed: number;
    closestMatch: string;
    biggestBlowout: string;
    // Awards
    mvp?: { playerId: UUID; playerName: string; stats: string };
    awards: ArchivedAward[];
    // Memorable moments
    highlights: string[];
    photoCount: number;
    coverPhotoUrl?: string;
    // Side games summary
    sideGamesSummary: ArchivedSideGame[];
    // Full data snapshot
    fullDataJson?: string; // Compressed JSON of complete trip data
    archivedAt: ISODateString;
}

export interface ArchivedPlayer {
    id: UUID;
    name: string;
    team: 'usa' | 'europe';
    handicap: number;
    record: { wins: number; losses: number; halves: number };
    points: number;
    isMvp: boolean;
}

export interface ArchivedAward {
    type: string;
    name: string;
    winnerId: UUID;
    winnerName: string;
    description?: string;
}

export interface ArchivedSideGame {
    name: string;
    type: string;
    winnerId?: UUID;
    winnerName?: string;
    totalPot: number;
}
