import Foundation
import SwiftData

/// Banter post for social feed
@Model
final class BanterPost {
    var id: UUID
    var content: String
    var authorId: String?  // Player ID if from a player
    var authorName: String
    var postType: String  // "message", "result", "lineup", "system"
    var emoji: String?
    var relatedMatchId: String?
    var timestamp: Date
    
    // Relationships
    var trip: Trip?
    
    init(
        id: UUID = UUID(),
        content: String,
        authorId: String? = nil,
        authorName: String,
        postType: String = "message",
        emoji: String? = nil,
        relatedMatchId: String? = nil,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.content = content
        self.authorId = authorId
        self.authorName = authorName
        self.postType = postType
        self.emoji = emoji
        self.relatedMatchId = relatedMatchId
        self.timestamp = timestamp
    }
}

extension BanterPost {
    /// Icon for post type
    var typeIcon: String {
        switch postType {
        case "result": return "trophy.fill"
        case "lineup": return "list.bullet.rectangle"
        case "system": return "info.circle"
        default: return "bubble.left.fill"
        }
    }
    
    /// Is this an auto-generated post?
    var isAutoGenerated: Bool {
        postType == "result" || postType == "lineup" || postType == "system"
    }
    
    /// Create a match result post
    static func matchResult(match: Match, teamAName: String, teamBName: String) -> BanterPost {
        let content: String
        switch match.result {
        case .teamAWin:
            content = "🏆 \(teamAName) wins \(match.margin)&\(match.holesRemaining)!"
        case .teamBWin:
            content = "🏆 \(teamBName) wins \(match.margin)&\(match.holesRemaining)!"
        case .halved:
            content = "🤝 Match halved - both teams earn 0.5 points"
        case .notFinished:
            content = "Match in progress"
        }
        
        return BanterPost(
            content: content,
            authorName: "System",
            postType: "result",
            relatedMatchId: match.id.uuidString
        )
    }
    
    /// Create a lineup published post
    static func lineupPublished(sessionName: String, captainName: String) -> BanterPost {
        return BanterPost(
            content: "📋 \(sessionName) lineup has been published!",
            authorName: captainName,
            postType: "lineup"
        )
    }
}
